# Generated by Django 4.0.4 on 2022-06-18 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, null=True)),
                ('course_id', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('attendanceState', models.CharField(choices=[('absent', 'Absent'), ('present', 'Present')], max_length=20, null=True)),
                ('start_date', models.DateField(default='2022-02-27')),
                ('week_num', models.CharField(blank=True, max_length=2)),
                ('end_date', models.DateField(default='2022-06-27')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('message', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(choices=[('Data Structure', 'Data Structure'), ('Computer Network', 'Computer Network'), ('Web Design', 'Web Design'), ('Internet of Things', 'Internet of Things'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Artificial Intelligence-Tut', 'Artificial Intelligence-Tut')], max_length=100, null=True)),
                ('date', models.DateField(max_length=20, null=True)),
                ('start_time', models.TimeField(max_length=20, null=True)),
                ('finish_time', models.TimeField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer_fname', models.CharField(max_length=100, null=True)),
                ('lecturer_lname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('password1', models.CharField(max_length=50, null=True)),
                ('password2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(null=True)),
                ('week_num', models.CharField(blank=True, max_length=2)),
                ('end_date', models.DateField(null=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_fname', models.CharField(max_length=100, null=True)),
                ('student_lname', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('image_name', models.ImageField(blank=True, upload_to='resources')),
                ('fk_course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LogInApp.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='fk_lecturer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LogInApp.lecturer'),
        ),
    ]
