# Generated by Django 4.0.4 on 2022-06-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='week_num',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
